[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "mkdir -p static",
  "python manage.py collectstatic --noinput"
]

[phases.build]
cmds = [
  "python manage.py migrate --noinput"
]

[start]
cmd = "daphne -b 0.0.0.0 -p $PORT vatimposter.asgi:application"

