[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate --noinput && daphne -b 0.0.0.0 -p $PORT vatimposter.asgi:application"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

