[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate --noinput && gunicorn vatimposter.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

